# Generated by Django 4.2.16 on 2025-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('bd', 'BD Team')], default=None, max_length=20, null=True),
        ),
    ]
