# Generated by Django 4.2.16 on 2025-11-10 09:12

import backend_app.drone_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('drone_type', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('uin_number', models.CharField(max_length=64, unique=True)),
                ('drone_serial_number', models.CharField(max_length=120, unique=True)),
                ('flight_controller_serial_number', models.CharField(blank=True, max_length=120)),
                ('remote_controller', models.CharField(blank=True, max_length=120)),
                ('battery_charger_serial_number', models.CharField(blank=True, max_length=120)),
                ('battery_serial_number_1', models.CharField(blank=True, max_length=120)),
                ('battery_serial_number_2', models.CharField(blank=True, max_length=120)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=backend_app.drone_registration.models.drone_attachment_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
