# Generated by Django 4.2.16 on 2025-11-12 06:51

import backend_app.drone_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneregistration',
            name='drone_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='droneregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend_app.drone_registration.models.drone_image_path),
        ),
        migrations.AddField(
            model_name='droneregistration',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
